### ISSUE TITLE
Send a friendship request to someone already sent you a request to you

### ISSUE THREAD

**Issue by efrapp** [misselliev/facebook-app#8]
I received a friendship request:
<img width="1421" alt="Screen Shot 2019-09-14 at 11 15 28 PM" src="https://user-images.githubusercontent.com/698811/64916677-604fc080-d747-11e9-8c72-03fdf382579c.png">

When I click in the "Add Friend" in the button I get the following view:

<img width="703" alt="Screen Shot 2019-09-14 at 11 15 57 PM" src="https://user-images.githubusercontent.com/698811/64916683-8d03d800-d747-11e9-9c07-162140a7e421.png">

**Comment by misselliev** [comment]
Implemented a fix for this, thank you!
