### ISSUE TITLE
Sign Up page for logged in user

### ISSUE THREAD

**Issue by efrapp** [misselliev/facebook-app#9]
When I go to the root url as a signed-in user I see this:

<img width="1131" alt="Screen Shot 2019-09-17 at 6 02 54 PM" src="https://user-images.githubusercontent.com/698811/65086048-f832f180-d975-11e9-811a-64ee5d956c29.png">

**Comment by misselliev** [comment]
Hi! We just implemented a fix that will show up on Milestone 6, thank you for pointing this out!
